#pragma once

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define MFIMAGELIB_LIB_NAME        "mfimage library"
#define MFIMAGELIB_VERSION_MAJOR   0
#define MFIMAGELIB_VERSION_MINOR   1
#define MFIMAGELIB_SERVICE_RELEASE 0
#define MFIMAGELIB_BUILDNO         /*@@@build@@@*/0

#define MFIMAGELIB_VERSION_STR     STR(MFIMAGELIB_VERSION_MAJOR) "." STR(MFIMAGELIB_VERSION_MINOR) "." STR(MFIMAGELIB_SERVICE_RELEASE)
#define MFIMAGELIB_VERSION_2_STR   MFIMAGELIB_VERSION_STR "." STR(MFIMAGELIB_BUILDNO)
#define MFIMAGELIB_ID              MFIMAGELIB_LIB_NAME " " MFIMAGELIB_VERSION_2_STR